// Copyright 2021 Stogl Robotics Consulting UG (haftungsbescrhänkt)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef IMPEDANCE_CONTROLLER_HPP_
#define IMPEDANCE_CONTROLLER_HPP_

#include <memory>
#include <string>
#include <vector>

#include "controller_interface/controller_interface.hpp"
#include "impedance_controller/visibility_control.h"
#include "rclcpp/subscription.hpp"
#include "rclcpp_lifecycle/node_interfaces/lifecycle_node_interface.hpp"
#include "rclcpp_lifecycle/state.hpp"
#include "realtime_tools/realtime_buffer.h"
#include "std_msgs/msg/float64_multi_array.hpp"

// auto-generated by generate_parameter_library
#include "impedance_controller_parameters.hpp"

#include <packbionics_interfaces/srv/update_impedance.hpp>
#include "impedance_controller/impedance_params.hpp"

namespace impedance_controller
{
using CmdType = std_msgs::msg::Float64MultiArray;
using SrvType = packbionics_interfaces::srv::UpdateImpedance;

/**
 * \brief Forward command controller for a set of joints and interfaces.
 *
 * This class forwards the command signal down to a set of joints or interfaces.
 *
 * Subscribes to:
 * - \b commands (std_msgs::msg::Float64MultiArray) : The commands to apply.
 */
class ImpedanceController : public controller_interface::ControllerInterface
{
public:
  IMPEDANCE_CONTROLLER_PUBLIC
  ImpedanceController();

  IMPEDANCE_CONTROLLER_PUBLIC
  ~ImpedanceController() = default;

  IMPEDANCE_CONTROLLER_PUBLIC
  controller_interface::InterfaceConfiguration command_interface_configuration() const override;

  IMPEDANCE_CONTROLLER_PUBLIC
  controller_interface::InterfaceConfiguration state_interface_configuration() const override;

  IMPEDANCE_CONTROLLER_PUBLIC
  controller_interface::CallbackReturn on_init() override;

  IMPEDANCE_CONTROLLER_PUBLIC
  controller_interface::CallbackReturn on_configure(
    const rclcpp_lifecycle::State & previous_state) override;

  IMPEDANCE_CONTROLLER_PUBLIC
  controller_interface::CallbackReturn on_activate(
    const rclcpp_lifecycle::State & previous_state) override;

  IMPEDANCE_CONTROLLER_PUBLIC
  controller_interface::CallbackReturn on_deactivate(
    const rclcpp_lifecycle::State & previous_state) override;

  IMPEDANCE_CONTROLLER_PUBLIC
  controller_interface::return_type update(
    const rclcpp::Time & time, const rclcpp::Duration & period) override;

protected:

  /**
   * Derived controllers have to declare parameters in this method.
   * Error handling does not have to be done. It is done in `on_init`-method of this class.
   */
  void declare_parameters();

  /**
   * Derived controllers have to read parameters in this method and set `command_interface_types_`
   * variable. The variable is then used to propagate the command interface configuration to
   * controller manager. The method is called from `on_configure`-method of this class.
   *
   * It is expected that error handling of exceptions is done.
   *
   * \returns controller_interface::CallbackReturn::SUCCESS if parameters are successfully read and
   * their values are allowed, controller_interface::CallbackReturn::ERROR otherwise.
   */
  controller_interface::CallbackReturn read_parameters();

  std::vector<std::string> joint_names_;
  std::string interface_name_;

  std::vector<std::string> command_interface_types_;

  realtime_tools::RealtimeBuffer<std::shared_ptr<CmdType>> rt_command_ptr_;

  rclcpp::Service<SrvType>::SharedPtr joints_command_service_;
  rclcpp::Subscription<CmdType>::SharedPtr joints_command_subscriber_;

  std::shared_ptr<ParamListener> param_listener_;
  Params params_;

private:
  void serviceCallback(const SrvType::Request::SharedPtr req, SrvType::Response::SharedPtr resp);

  double computeCommand(double position, double velocity, const ImpedanceParams &params);

  std::vector<ImpedanceParams> impedance_params_;
};

}  // namespace impedance_controller

#endif  // IMPEDANCE_CONTROLLER_HPP_